### ISSUE TITLE
Realtime Table

### ISSUE THREAD

**Issue by dullibri** [dullibri/if_license_plates_could_talk#1]
@moritz-hl: In order to use the attributes for historic events it is necessary to get:
- real-time date at least every 5-years
- the changing regional level (harz) need to be considered.

**Comment by moritz-hl** [comment]
Done:
- Data on crimes is available for the years 2013-2018. It seems that there is no (publicly available) data for earlier years (at least on regional level)
- Data on income is available for the years 2003-2020 (and possibly even earlier)
- (Using geopandas,) one can fix issues concerning changing regional levels
